---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_vm_folder }}"
      name: "{{ vmName }}"
      state: poweredon
      template: Windows2016Template
      customization_spec: "{{ windows_customization_spec }}"
      networks:
      - name: "{{ vcenter_network_name }}"
        ip: "{{ VMIP }}"
        netmask: "255.255.255.0" 
        gateway: "192.168.178.1"
      wait_for_ip_address: no
      wait_for_customization: "{{ wait_for_customization }}"
    register: deploy
