---
- name: Hello World Sample Windows
  hosts: windows_hosts
  tasks:
        - name: See if window can be reached
          win_ping:

        - name: Copy file over to windows host
          win_copy:
                src: /etc/krb5.conf
                dest: C:\Temp\krb5.conf
