---
- name: Group, and User (Member of Group)
  hosts: all
  tasks:
  # Note: can't create an OU yet, very diffcult. (Creating an OU won't come up that often anyway though.)
  # So be sure the path is an existing OU.
  - name: Ensure the group "test" exists
    win_domain_group:
      name: TestGroup
      path: OU=TestOU,DC=dwrolvink,DC=com
      scope: global
      state: present
      
  - name: Ensure user bob is present in test OU, and is member of TestGroup
    win_domain_user:
      name: bob
      password: B0bP4ssw0rd
      state: present
      path: OU=TestOU,DC=dwrolvink,DC=com
      groups:
        - TestGroup
